name: Back Merge from Master
on: 
  pull_request:
    branches: [master]
    types: [closed]
  push:
    branches: [master]
jobs:
  job-merge-master-to-staging:
    if: github.event.pull_request.merged == true || github.event_name == 'push'
    timeout-minutes: 2
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set Git config
      run: |
          git config --local user.email "nithin@getwyld.in"
          git config --local user.name "Nithin Vasishta (GHA)"
    - name: Merge master back to staging
      id: merge-master-staging
      uses: everlytic/branch-merge@1.1.2
      with:
        github_token: ${{ github.token }}
        source_ref: ${{ github.ref }}
        target_branch: 'staging'
        commit_message_template: '[Automated] Merged {source_ref} into target {target_branch}'
    - name: Log merge output
      id: log-output
      run: | 
          if ${{steps.merge-master-staging.outcome == 'success'}}; then
            echo "merge_error=false" >> $GITHUB_OUTPUT          
          else
            echo "merge_error=true" >> $GITHUB_OUTPUT          
          fi
    outputs:
      merge-conflict: ${{ steps.log-output.outputs.merge_error }}
  email-merge-conflict-1:
    runs-on: ubuntu-latest
    needs: job-merge-master-to-staging
    if: ${{ needs.job-merge-master-to-staging.outputs.merge-conflict  == 'true'}}
    steps:
      - name: Send email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtppro.zoho.com
          server_port: 465
          secure: true
          username: nithin@getwyld.in
          password: ${{secrets.MAIL_PASSWORD}}
          subject: Back Merge Failed (Master to Staging)
          to: nithin@getwyld.in
          from: nithin@getwyld.in
          body: Merge from master to staging not successful due to merge conflicts
  job-merge-master-to-dev:
    if: github.event.pull_request.merged == true || github.event_name == 'push'
    timeout-minutes: 2
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set Git config
      run: |
          git config --local user.email "nithin@getwyld.in"
          git config --local user.name "Nithin Vasishta (GHA)"
    - name: Merge master back to dev
      id: merge-master-dev
      uses: everlytic/branch-merge@1.1.2
      with:
        github_token: ${{ github.token }}
        source_ref: ${{ github.ref }}
        target_branch: 'development'
        commit_message_template: '[Automated] Merged {source_ref} into target {target_branch}'
    - name: Log merge output
      id: log-output
      run: | 
          if ${{steps.merge-master-dev.outcome == 'success'}}; then
            echo "merge_error=false" >> $GITHUB_OUTPUT          
          else
            echo "merge_error=true" >> $GITHUB_OUTPUT          
          fi
    outputs:
      merge-conflict: ${{ steps.log-output.outputs.merge_error }}
  email-merge-conflict-2:
    runs-on: ubuntu-latest
    needs: job-merge-master-to-dev
    if: ${{ needs.job-merge-master-to-dev.outputs.merge-conflict  == 'true'}}
    steps:
      - name: Sanity check
        run: |
          echo "Need to send email"
          echo ${{ needs.job-merge-master-to-dev.outputs.merge-conflict }}
      - name: Send email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtppro.zoho.com
          server_port: 465
          secure: true
          username: nithin@getwyld.in
          password: ${{secrets.MAIL_PASSWORD}}
          subject: Back Merge Failed (Master to Staging)
          to: nithin@getwyld.in,tech@getwyld.in
          from: nithin@getwyld.in
          body: Merge from master to staging not successful due to merge conflicts
