name: Back Merge from Master
on: 
  pull_request:
    branches: [master]
    types: [closed]
  push:
    branches: [master]
jobs:
  job-merge-master-to-staging:
    if: github.event.pull_request.merged == true || github.event_name == 'push'
    timeout-minutes: 2
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set Git config
      run: |
          git config --local user.email "nithin@getwyld.in"
          git config --local user.name "Nithin Vasishta (GHA)"
    - name: Merge master back to staging
      id: merge-master-staging
      uses: nithin-wyld/branch-merge@master
      with:
        github_token: ${{ github.token }}
        source_ref: ${{ github.ref }}
        target_branch: 'staging'
        commit_message_template: '[Automated] Merged {source_ref} into target {target_branch}'
  email-merge-conflict-1:
    runs-on: ubuntu-latest
    needs: job-merge-master-to-staging
    if: ${{ failure() }}
    steps:
      - name: Send email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtppro.zoho.com
          server_port: 465
          secure: true
          username: nithin@getwyld.in
          password: ${{secrets.MAIL_PASSWORD}}
          subject: Back Merge Failed (Master to Staging)
          to: nithin@getwyld.in
          from: nithin@getwyld.in
          body: Merge from master to staging not successful due to merge conflicts
  job-merge-master-to-dev:
    if: github.event.pull_request.merged == true || github.event_name == 'push'
    timeout-minutes: 2
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set Git config
      run: |
          git config --local user.email "nithin@getwyld.in"
          git config --local user.name "Nithin Vasishta (GHA)"
    - name: Merge master back to dev
      id: merge-master-dev
      uses: nithin-wyld/branch-merge@master
      with:
        github_token: ${{ github.token }}
        source_ref: ${{ github.ref }}
        target_branch: 'development'
        commit_message_template: '[Automated] Merged {source_ref} into target {target_branch}'
  email-merge-conflict-2:
    runs-on: ubuntu-latest
    needs: job-merge-master-to-dev
    if: ${{ failure() }}
    steps:
      - name: Send email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtppro.zoho.com
          server_port: 465
          secure: true
          username: nithin@getwyld.in
          password: ${{secrets.MAIL_PASSWORD}}
          subject: Back Merge Failed (Master to Dev)
          to: nithin@getwyld.in,tech@getwyld.in
          from: nithin@getwyld.in
          body: Merge from master to dev not successful due to merge conflicts
