name: Back Merge from Master
on: 
  pull_request:
    branches: [master]
    types: [closed]
  push:
    branches: [master]
jobs:
  job-merge-master-to-staging:
    if: github.event.pull_request.merged == true || github.event_name == 'push'
    timeout-minutes: 2
    runs-on: ubuntu-latest
    outputs:
      merge-conflict: ${{ steps.merge-master-staging.outputs.merge_error }}
    steps:
    - uses: actions/checkout@v3
    - name: Set Git config
      run: |
          git config --local user.email "nithin@getwyld.in"
          git config --local user.name "Nithin Vasishta (GHA)"
    - name: Merge master back to staging
      id: merge-master-staging
      run: |
          git fetch --unshallow
          git checkout staging
          git pull
          git merge --no-ff master -m "Auto-merge master back to staging"
          export conflicts=$(grep -lr -r -E -- '^<<<<<<<|^>>>>>>>' .)
          if [ -n "$conflicts" ]; then
            echo "merge_error=true" >> $GITHUB_OUTPUT
          else
            echo "merge_error=false" >> $GITHUB_OUTPUT
            git push
          fi
  email-merge-conflict-1:
    runs-on: ubuntu-latest
    needs: job-merge-master-to-staging
    if: ${{ needs.job-merge-master-back-to-dev.outputs.merge-conflict }} == "true"
    steps:
      - name: Sanity check
        run: |
          echo "Need to send email"
      - name: Send email
        uses: devellany/send-mailer@v1.0.2
        with:
          host: smtp.google.com
          account: ${{secrets.ACCOUNT}}
          password: ${{secrets.MAIL_PASSWORD}}
          sender: Github Actions
          from: ${{secrets.MAIL_ADDRESS}}
          to: nithin@getwyld.in
          subject: Back Merge Failed (Master to Staging)
          body: Merge from master to staging not successful due to merge conflicts
  job-merge-master-to-dev:
    if: github.event.pull_request.merged == true || github.event_name == 'push'
    timeout-minutes: 2
    runs-on: ubuntu-latest
    outputs:
      merge-conflict: ${{ steps.merge-master-dev.outputs.merge_error }}
    steps:
    - uses: actions/checkout@v3
    - name: Set Git config
      run: |
          git config --local user.email "nithin@getwyld.in"
          git config --local user.name "Nithin Vasishta (GHA)"
    - name: Merge master back to dev
      id: merge-master-dev
      run: |
          git fetch --unshallow
          git checkout development
          git pull
          git merge --no-ff master -m "Auto-merge master back to dev"
          export conflicts=$(grep -lr -r -E -- '^<<<<<<<|^>>>>>>>' .)
          if [ -n "$conflicts" ]; then
            echo "merge_error=true" >> $GITHUB_OUTPUT
          else
            echo "merge_error=false" >> $GITHUB_OUTPUT
            git push
          fi
  email-merge-conflict-2:
    runs-on: ubuntu-latest
    needs: job-merge-master-to-dev
    if: ${{ needs.job-merge-master-back-to-dev.outputs.merge-conflict }} == "true"
    steps:
      - name: Sanity check
        run: |
          echo "Need to send email"
      - name: Send email
        uses: devellany/send-mailer@v1.0.2
        with:
          host: smtp.google.com
          account: ${{secrets.ACCOUNT}}
          password: ${{secrets.MAIL_PASSWORD}}
          sender: Github Actions
          from: ${{secrets.MAIL_ADDRESS}}
          to: nithin@getwyld.in
          subject: Back Merge Failed (Master to Dev)
          body: Merge from master to dev not successful due to merge conflicts
