name: Test If Condition
on: [pull_request]
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Set merge_error
        id: set-merge-error
        run: |
            echo "merge_error=false" >> $GITHUB_OUTPUT      
    outputs:
      merge-conflict: ${{ steps.set-merge-error.outputs.merge_error }}
  check-1:
    runs-on: ubuntu-latest
    needs: job1
    if: ${{ needs.job1.outputs.merge-conflict == 'true' }}
    steps:
      - name: Echo result
        run: |
            echo "Merge conflict"
            echo ${{ needs.job1.outputs.merge-conflict }}
  check-2:
    runs-on: ubuntu-latest
    needs: job1
    if: ${{ needs.job1.outputs.merge-conflict == 'false' }}
    steps:
      - name: Echo result
        run: |
            echo "No Merge conflict"
            echo ${{ needs.job1.outputs.merge-conflict }}
