name: Send Email
on: [pull_request, push]
jobs:
  send-email:
    runs-on: ubuntu-latest
    steps:
      - name: Send email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: nithin127vasishta@gmail.com
          password: ${{secrets.MAIL_PASSWORD_GMAIL}}
          subject: Testing
          to: nithin@getwyld.in
          from: nithin127vasishta@gmail.com
          body: Testing 123
