name: Send Email
on: []
jobs:
  send-email:
    runs-on: ubuntu-latest
    steps:
      - name: Send email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtppro.zoho.com
          server_port: 465
          secure: true
          username: nithin@getwyld.in
          password: ${{secrets.MAIL_PASSWORD}}
          subject: Testing
          to: nithin@getwyld.in
          from: nithin127vasishta@gmail.com
          body: Testing 222123
